import {RELEASE,RESOURCE_LABELS,RESOURCE_SYMBOLS,RESOURCES,TOOLS,WORKERS,CONTRACTS,QUESTS,EVENTS,ACHIEVEMENTS,ICONS} from './data.js';
import {createGame,checkState,action,purchase,hire,fire,trade,fulfill,claimQuest,chooseEvent,simulate,advanceOffline,levelForXp,maxEnergy,caps,workerSlots,totalWorkers,workerCost,stageName,currentStage,marketPrice,buyPrice,canAfford,rates,setReserve} from './engine.js';
import {loadGame,saveQuick,saveGame,backupGame,exportJson,parseImport} from './storage.js';

let game,tab='home',modal=null,offlineResult=null,lastTick=Date.now(),lastDraw=0,lastSave=Date.now(),lastBackup=Date.now(),writeTimer=null,toastTimer=null,toastId=0;
const ROOT=document.getElementById('app');
const fmt=v=>Math.floor(Math.max(0,v)+1e-8).toLocaleString('es-ES');
const compact=v=>Math.abs(v)>=100000?Intl.NumberFormat('es-ES',{notation:'compact',maximumFractionDigits:1}).format(v):fmt(v);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const costText=(c,isReward=false)=>Object.entries(c||{}).map(([r,n])=>`<span class="costtag ${!isReward&&r!=='xp'&&game.resources[r]+1e-8<n?'not-enough':''}">${r==='xp'?'✦':ICONS[r]} ${fmt(n)} ${r==='xp'?'XP':RESOURCE_LABELS[r]?.toLowerCase()||r}</span>`).join('');
const btn=(label,d,klass='primary',disabled=false,extra='')=>`<button class="${klass}" data-do="${d}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
const navs=[{id:'home',icon:'⌂',label:'Inicio'},{id:'work',icon:'⚒',label:'Oficios'},{id:'shop',icon:'▣',label:'Mejoras'},{id:'market',icon:'⚖',label:'Mercado'},{id:'chron',icon:'📜',label:'Crónica'}];
function navigation(mobile=false){return `<nav class="${mobile?'mobile-nav':'navlist'}" aria-label="Navegación principal">${navs.map(n=>`<button class="navbtn ${tab===n.id?'active':''}" aria-current="${tab===n.id?'page':'false'}" data-do="tab" data-id="${n.id}"><span class="nav-ico" aria-hidden="true">${n.icon}</span><span class="nav-label">${n.label}</span></button>`).join('')}</nav>`;}
function initShell(){ROOT.innerHTML=`<aside class="sidebar"><div class="brand"><div class="brand-mark">♛</div><div><h1>DE MENDIGO<br>A EMPERADOR</h1><small>CRÓNICAS DEL BARRO</small></div></div>${navigation(false)}<div class="sidebar-bottom"><span id="save-status">● Preparando guardado</span><br>Versión ${RELEASE} · Prólogo</div></aside><header class="topbar"><div class="top-title"><div><div class="eyebrow" style="font-size:9px">CRÓNICAS DEL BARRO · v${RELEASE}</div><div class="top-sub">Del polvo del camino a las primeras monedas</div></div><span id="stage-tag" class="stage-badge"></span></div><div id="resource-strip" class="statbar"></div></header><main id="page" class="content" tabindex="-1"></main>${navigation(true)}<div id="toasts" class="toast-wrap" aria-live="polite"></div><div id="modal-area"></div><input id="import-file" type="file" accept="application/json,.json" class="sr-only" aria-label="Importar archivo de partida">`;
  document.addEventListener('click',handleClick);
  document.getElementById('import-file').addEventListener('change',handleFile);
}
function ratesLabel(r){let n=rates(game)[r];if(Math.abs(n)<.001)return '';return `<span class="stat-rate" style="color:${n>=0?'var(--green)':'var(--red)'}">${n>=0?'+':''}${n.toFixed(2)}/s</span>`;}
function resourceStrip(){return ['gold','food','wood'].map(r=>`<div class="stat-pill ${r}"><div class="stat-name">${ICONS[r]} ${RESOURCE_LABELS[r]}</div><div class="stat-number">${compact(game.resources[r])}</div>${ratesLabel(r)}</div>`).join('');}
function progress(label,n,max,type=''){return `<div><div class="progress-label"><span>${label}</span><b>${fmt(n)} / ${fmt(max)}</b></div><div class="progress-track"><div class="progress-fill ${type}" style="width:${Math.max(0,Math.min(100,n/max*100))}%"></div></div></div>`;}
function elapsedText(t){let m=Math.floor(Math.max(0,t)/60),h=Math.floor(m/60);return h?`${h} h ${m%60} min`:`${m} min`}
function eventBanner(){const e=EVENTS.find(e=>e.id===game.pendingEvent);return e?`<div class="event-banner"><div><strong>✉ ${esc(e.title)}</strong><p>Un acontecimiento está esperando tu decisión.</p></div>${btn('Decidir →','open-event','outline')}</div>`:'';}
function hero(){const st=currentStage(game);const next=st===1?'Levanta tu primer refugio y contrata ayuda.':st===2?'Construye un puesto para empezar a comerciar.':'Has terminado el prólogo. Tu historia continúa en la v0.2.';
  return `<section class="hero stage${st}"><span class="star">✦</span><div class="hero-foreground"><span class="pill">CAPÍTULO ${['','I','II','III'][st]} · ${stageName(game).toUpperCase()}</span><h2>${st===1?'Todo imperio comienza en el barro.':st===2?'Ya no caminas en soledad.':'Un nombre entre mercaderes.'}</h2><p>${next}</p><div class="hero-bottom"><span class="hero-badge">✦ Nivel ${levelForXp(game.xp)}</span><span class="hero-badge">⚒ ${totalWorkers(game)} trabajadores</span></div></div></section>`;}
function questPanel(limit=3){const waiting=QUESTS.filter(q=>!game.completed.includes(q.id));const ready=waiting.filter(q=>q.check(game));let selected=[...ready,...waiting.filter(q=>!q.check(game))].slice(0,limit);
return `<div class="panel"><div class="row between"><h2>Tu camino</h2><span class="pill gray">${game.completed.length}/${QUESTS.length}</span></div><p class="panel-desc">Completa objetivos para obtener recursos y experiencia.</p>${selected.length?selected.map(q=>`<div class="quest-item"><div class="mark">${q.check(game)?'✦':'◇'}</div><div class="quest-body"><div class="quest-title">${q.title}</div><div class="quest-text">${q.desc}</div><div class="quest-reward">${costText(q.reward,true)}</div></div>${q.check(game)?btn('Cobrar','claim','secondary smallbtn',false,`data-id="${q.id}"`):''}</div>`).join(''):`<div class="notice">¡Has completado todos los objetivos disponibles de esta versión! 👑</div>`}</div>`;}
function recentLog(limit=5){return `<div class="panel"><div class="row between"><h2>Tu diario</h2><span class="subtle small">Sucesos recientes</span></div><div class="timeline">${game.log.slice(0,limit).map(x=>`<div class="timeline-item"><span class="timeline-time">${elapsedText(x.at)}</span><span class="timeline-text ${esc(x.type)}">${esc(x.message)}</span></div>`).join('')}</div></div>`;}
function meters(){const rate=rates(game);return `<div class="panel"><h2>Estado del viajero</h2><p class="panel-desc">Trabaja, come y descansa. El tiempo recupera tu energía.</p><div class="progress-group">${progress('⚡ Energía',game.energy,maxEnergy(game),'goldfill')}${progress('🍞 Saciedad',game.hunger,100,game.hunger<25?'redfill':'')}${progress('✦ Progreso de nivel',game.xp-Math.pow(levelForXp(game.xp)-1,2)*36, (2*levelForXp(game.xp)-1)*36)}</div><div class="row" style="margin-top:17px;flex-wrap:wrap">${btn((game.restCooldown||0)>0?`☕ ${Math.ceil(game.restCooldown)}s`:'☕ Descansar','work','secondary',(game.restCooldown||0)>0||game.energy>=maxEnergy(game)-.02,'data-id="rest"')}${btn('🍞 Comer 1 ración','work','outline',game.resources.food<1||game.hunger>=99.9,'data-id="eat"')}</div><div class="divider"></div><div class="row between"><span class="subtle">Experiencia total</span><strong>✦ ${fmt(game.xp)} XP</strong></div><div class="row between" style="margin-top:8px"><span class="subtle">Energía recuperada</span><span class="positive">${((game.owned.shelter ? 0.34 : 0.24)*(game.owned.blanket ? 1.25 : 1)*(game.owned.hearth ? 1.15 : 1)*(game.hunger<14 ? 0.65 : 1)).toFixed(2)}/s</span></div></div>`;}
function actionRows(compactMode=false){const actions=[{id:'beg',icon:'🤲',title:'Mendigar',description:'Habla con los viajeros y recoge unas monedas.',effect:'+2–5 monedas · +3 XP',cost:1},{id:'forage',icon:'🌾',title:'Buscar provisiones',description:'Recoge alimentos y, de vez en cuando, hierbas.',effect:`+${2+(game.owned.basket?1:0)}–${3+(game.owned.basket?1:0)} comida · +4 XP`,cost:1.5},{id:'wood',icon:'🪵',title:'Recoger madera',description:'Recoge ramas y vende la madera sobrante.',effect:`+${2+(game.owned.axe?2:0)}–${3+(game.owned.axe?2:0)} madera · +4 XP`,cost:2},{id:'stone',icon:'🪨',title:'Extraer piedra',description:'Necesitas un pico para trabajar en la cantera.',effect:'+2–3 piedra · +5 XP',cost:2.5,unlock:!!game.owned.pickaxe},{id:'errand',icon:'✉️',title:'Hacer un encargo',description:'Trabaja para un mercader del camino.',effect:'+15–23 monedas · +8 XP',cost:3.5,unlock:game.stats.goldEarned>=75}];
  return actions.filter(a=>a.unlock!==false||!compactMode).map(a=>`<div class="action-row ${a.unlock===false?'blocked':''}"><div class="action-emoji">${a.icon}</div><div class="action-info"><strong>${a.title}</strong><div class="item-desc">${compactMode?'':a.description}</div><div class="reward">${a.unlock===false?'🔒 Por desbloquear':a.effect}</div></div>${btn(a.unlock===false?'🔒':`−${a.cost} ⚡`,'work','primary smallbtn',a.unlock===false||game.energy+1e-8<a.cost,`data-id="${a.id}" aria-label="${a.title}"`)}</div>`).join('');}
function overview(){return `${eventBanner()}${hero()}<div class="section-head"><h2 class="section-title">Tu jornada</h2><span>Acciones principales</span></div><div class="two-col"><div class="stack"><section class="panel"><div class="row between"><h2>Gánate la vida</h2><span class="pill gray">${game.stats.actions} acciones</span></div><p class="panel-desc">Cada acción mejora tu situación. No te preocupes: pronto podrás automatizarlas.</p><div class="action-list">${actionRows(true)}</div><div style="margin-top:14px">${btn('Ver todos los oficios →','tab','ghost full',false,'data-id="work"')}</div></section>${questPanel()}</div><div class="stack">${meters()}${recentLog(5)}</div></div>`;}
function workPage(){const slots=workerSlots(game),used=totalWorkers(game);return `${eventBanner()}<div class="dashboard-header"><h2>Oficios y trabajadores</h2><p>De tus manos nace la riqueza. Con ayuda, el trabajo continúa incluso cuando no juegas.</p></div><div class="two-col"><div class="stack"><section class="panel"><div class="row between"><h2>Trabajo manual</h2><span class="pill">✦ Nivel ${levelForXp(game.xp)}</span></div><p class="panel-desc">Consigue recursos, experiencia y dinero para tus primeras inversiones.</p><div class="action-list">${actionRows()}</div></section><section class="panel"><div class="row between"><h2>Tu equipo</h2><span class="pill ${game.owned.shelter?'green':'gray'}">${used}/${slots} plazas</span></div><p class="panel-desc">Los empleados generan recursos automáticamente y cobran salarios por la producción realizada.</p>${!game.owned.shelter?`<div class="locked-banner">🔒 Construye un refugio para contratar a tus primeros trabajadores.</div>`:`<div class="item-list">${WORKERS.map(w=>`<div class="item-row ${!game.owned[w.req]?'blocked':''}"><div class="action-emoji">${w.icon}</div><div class="item-info"><strong>${w.name}</strong><div class="item-desc">${w.desc}</div><div class="item-desc">Sueldo: ${w.wage.toFixed(3)} monedas/s por empleado</div>${w.id==='trader'?`<div class="item-desc">Reserva: ${fmt(game.reserveWood)} madera</div>`:''}</div><div class="item-right"><div class="worker-controls">${btn('−','fire','ghost smallbtn',!(game.workers[w.id]>0),`data-id="${w.id}" aria-label="Despedir ${w.name}"`)}<span class="count">${game.workers[w.id]}</span>${btn('+','hire','primary smallbtn',!game.owned[w.req]||used>=slots||game.resources.gold<workerCost(game,w.id),`data-id="${w.id}" aria-label="Contratar ${w.name}"`)}</div><span class="price">${fmt(workerCost(game,w.id))} 🪙</span></div></div>`).join('')}</div>`}${game.owned.stall?`<div class="divider"></div><div class="inputrow"><label for="reserve">Reserva de madera para el vendedor</label><input id="reserve" type="number" min="0" max="${caps(game).wood}" value="${fmt(game.reserveWood)}"><button class="secondary smallbtn" data-do="reserve">Aplicar</button></div>`:''}</section></div><div class="stack">${meters()}<section class="panel"><h2>Producción estimada</h2><p class="panel-desc">Ingresos y consumos de tus trabajadores, antes de límites de almacén.</p>${RESOURCES.map(r=>`<div class="row between" style="margin:9px 0"><span>${ICONS[r]} ${RESOURCE_LABELS[r]}</span><strong class="${rates(game)[r]>=0?'positive':'negative'}">${rates(game)[r]>=0?'+':''}${rates(game)[r].toFixed(3)}/s</strong></div>`).join('')}<p class="subtle tiny">Los trabajadores sin insumos, sin fondos o con el almacén lleno pueden detenerse.</p></section></div></div>`;}
function shopPage(){return `${eventBanner()}<div class="dashboard-header"><h2>Herramientas y construcciones</h2><p>Una buena inversión cambia lo que eres capaz de hacer. Cada mejora se compra una sola vez.</p></div><div class="shop-grid">${TOOLS.map(t=>{let locked=currentStage(game)<t.tier,owned=game.owned[t.id],afford=canAfford(game,t.cost);return `<div class="shop-card ${owned?'owned':''} ${locked?'blocked':''}"><div class="row between"><span class="shop-card-icon">${t.icon}</span><span class="pill ${owned?'green':'gray'}">${owned?'✓ Adquirido':locked?'🔒 Etapa II':t.tier===2?'TRABAJADOR':'MENDIGO'}</span></div><h3>${t.name}</h3><div class="item-desc">${t.desc}</div><div class="badges">${costText(t.cost)}</div><div class="btnrow">${btn(owned?'✓ Construido':locked?'Bloqueado':'Construir / comprar','purchase',owned?'ghost full':'primary full',locked||owned||!afford,`data-id="${t.id}"`)}</div></div>`}).join('')}</div><p class="footer-note">Consejo: vender madera suele ser más rentable que mendigar constantemente. Pero reserva materiales para tus construcciones.</p>`;}
function marketPage(){return `${eventBanner()}<div class="dashboard-header"><h2>Mercado y encargos</h2><p>Los precios cambian con el tiempo. Vende excedentes, compra lo que necesitas y completa contratos.</p></div><div class="section-head"><h2 class="section-title">Compra y vende</h2><span>Precios del mercado local</span></div><div class="market-grid">${['food','wood','stone','herbs'].map(r=>`<div class="market-item"><div class="row between"><h3>${ICONS[r]} ${RESOURCE_LABELS[r]}</h3><span class="pill gray">${fmt(game.resources[r])}/${fmt(caps(game)[r])}</span></div><div class="market-price">Venta: ${marketPrice(game,r)} 🪙 · Compra: ${buyPrice(game,r)} 🪙</div><div class="market-actions">${btn('Vender 1','trade','secondary smallbtn',game.resources[r]<1,`data-id="${r}" data-kind="sell" data-q="1"`)}${btn('Vender 5','trade','secondary smallbtn',game.resources[r]<1,`data-id="${r}" data-kind="sell" data-q="5"`)}${btn('Todo','trade','outline smallbtn',game.resources[r]<1,`data-id="${r}" data-kind="sell" data-q="all"`)}${btn('Comprar 1','trade','ghost smallbtn',game.resources.gold<buyPrice(game,r)||caps(game)[r]-game.resources[r]<1,`data-id="${r}" data-kind="buy" data-q="1"`)}</div></div>`).join('')}</div><div class="section-head"><h2 class="section-title">Tablón de encargos</h2><span>Nuevas ofertas en ${Math.ceil(game.contractTimer/60)} min</span></div><div class="three-col">${game.contracts.length?game.contracts.map(c=>`<div class="contract"><h3>✉ ${c.name}</h3><div class="contract-cost">${costText(c.needs)}</div><div class="contract-footer"><span class="reward">+${fmt(c.reward)} 🪙 · +15 XP</span>${btn('Entregar','contract','primary smallbtn',!canAfford(game,c.needs),`data-id="${c.uid}"`)}</div></div>`).join(''):`<div class="notice">No quedan encargos. El tablón se renovará pronto.</div>`}</div><div class="notice info" style="margin-top:16px">💡 Los contratos ofrecen pagos fijos y pueden ser muy rentables. Se renuevan periódicamente y no obligan a estar conectado.</div>`;}
function chronPage(){const level=levelForXp(game.xp);return `${eventBanner()}<div class="dashboard-header"><h2>Libro de las Crónicas</h2><p>Las grandes historias también empiezan con botas gastadas y un poco de suerte.</p></div><div class="panel"><div class="eyebrow">CAPÍTULO ACTUAL</div><h2 style="margin-top:8px">${currentStage(game)===3?'El primer comerciante':currentStage(game)===2?'Un oficio honrado':'El mendigo del camino'}</h2><p class="quote">«${currentStage(game)===3?'Con tu primer puesto comercial, tu nombre comienza a correr entre viajeros y gremios. El siguiente capítulo traerá talleres, rutas y negocios.':currentStage(game)===2?'Tu refugio ya no es solo un techo: es el principio de una comunidad que depende de tus decisiones.':'No poseías tierras, ni nombre, ni escudo. Aun así, decidiste construir algo que sobreviviera a tus primeros pasos.'}»</p></div><div class="section-head"><h2 class="section-title">Tu historia en cifras</h2></div><div class="chron-stats">${[{n:'Tiempo jugado',v:elapsedText(game.clock)},{n:'Monedas ganadas',v:fmt(game.stats.goldEarned)},{n:'Experiencia',v:`${fmt(game.xp)} XP`},{n:'Acciones manuales',v:fmt(game.stats.actions)},{n:'Contratos',v:fmt(game.stats.contracts)},{n:'Trabajadores',v:fmt(totalWorkers(game))}].map(x=>`<div class="chron-stat"><span>${x.n}</span><b>${x.v}</b></div>`).join('')}</div><div class="section-head"><h2 class="section-title">Logros</h2><span>${game.achievements.length} / ${ACHIEVEMENTS.length}</span></div><div class="achievement-grid">${ACHIEVEMENTS.map(a=>`<div class="achievement ${game.achievements.includes(a.id)?'earned':''}"><div class="achievement-icon">${game.achievements.includes(a.id)?'🏅':'🔒'}</div><div><strong>${a.name}</strong><p>${a.desc}</p></div></div>`).join('')}</div><div class="section-head"><h2 class="section-title">Objetivos y recompensas</h2></div>${questPanel(QUESTS.length)}<div class="section-head"><h2 class="section-title">Guardado y seguridad</h2></div><section class="panel"><p class="panel-desc">Tu partida se guarda automáticamente en este navegador. Exporta una copia para moverla entre dispositivos o protegerte si borras los datos de Safari.</p><div class="save-actions">${btn('↓ Exportar partida','export','secondary')}${btn('↑ Importar partida','import','outline')}${btn('Guardar ahora','save','ghost')}</div><div class="divider"></div><div class="row between wrap"><span class="subtle small">Autoguardado activo · v${RELEASE}</span>${btn('Reiniciar partida','reset','ghost smallbtn')}</div><p class="footer-note">GitHub Pages no sincroniza partidas entre PC y iPhone. Exporta el archivo para transferir tu progreso. No borres los datos del navegador sin copia de seguridad.</p></section><div class="section-head"><h2 class="section-title">Diario completo</h2></div>${recentLog(24)}`;}
function pageHtml(){return ({home:overview,work:workPage,shop:shopPage,market:marketPage,chron:chronPage}[tab]||overview)();}
function draw(){document.getElementById('stage-tag').textContent=`✦ ${stageName(game)}`;document.getElementById('resource-strip').innerHTML=resourceStrip();document.getElementById('page').innerHTML=pageHtml();document.querySelectorAll('.navbtn').forEach(b=>{b.classList.toggle('active',b.dataset.id===tab);b.setAttribute('aria-current',b.dataset.id===tab?'page':'false')});drawModal();lastDraw=Date.now();}
function toast(message,isError=false){const c=document.getElementById('toasts');const elem=document.createElement('div');elem.className=`toast ${isError?'error':''}`;elem.textContent=message;c.prepend(elem);setTimeout(()=>elem.remove(),3500);}
function queueSave(){const ok=saveQuick(game);const el=document.getElementById('save-status');if(el)el.textContent=ok?'● Guardado local actualizado':'● Guardado local limitado';if(writeTimer)clearTimeout(writeTimer);writeTimer=setTimeout(async()=>{const good=await saveGame(game);if(el)el.textContent=good?'● Partida guardada':'● Guarda una copia exportada';},750);}
function eventModal(){const e=EVENTS.find(x=>x.id===game.pendingEvent);if(!e)return '';return `<div class="eyebrow">ACONTECIMIENTO</div><h2>${e.title}</h2><p>${e.text}</p>${e.choices.map((c,i)=>`<button class="choice-btn" data-do="choice" data-id="${e.id}" data-q="${i}" ${!canAfford(game,c.cost)?'disabled':''}><strong>${c.title}</strong><small>${c.desc}${Object.keys(c.cost).length?` · Requiere ${Object.entries(c.cost).map(([r,n])=>`${n} ${RESOURCE_LABELS[r]}`).join(', ')}`:''}</small></button>`).join('')}`;}
function drawModal(){const area=document.getElementById('modal-area');if(!modal){area.innerHTML='';return;}let content='';let closable=true;
 if(modal==='event'){content=eventModal();}
 if(modal==='welcome'){content=`<div class="eyebrow">TU PRIMERA HISTORIA</div><h2>Del barro a la corona</h2><p>Hoy eres un mendigo a la orilla del camino. Trabaja para ganar recursos, vende madera, compra herramientas y construye un refugio. Después podrás contratar gente que trabajará incluso cuando cierres el juego.</p><div class="notice info">Empieza en <b>Inicio</b> o <b>Oficios</b>. Los botones dorados son tus acciones. Los trabajos gastan energía, que vuelve sola; también puedes descansar.</div>`;}
 if(modal==='offline'&&offlineResult){let d=offlineResult;content=`<div class="eyebrow">BIENVENIDO DE VUELTA</div><h2>Tu equipo ha seguido trabajando</h2><p>Has estado fuera aproximadamente <strong>${elapsedText(d.real)}</strong>. Contabilizamos el equivalente a <strong>${elapsedText(d.effective)}</strong> de producción.</p><div class="item-list">${Object.entries(d.changes).filter(([r,x])=>Math.abs(x)>.1).map(([r,x])=>`<div class="row between"><span>${ICONS[r]} ${RESOURCE_LABELS[r]}</span><b class="${x>=0?'positive':'negative'}">${x>=0?'+':''}${fmt(Math.abs(x))}</b></div>`).join('')||'<p class="subtle">Todavía no tienes trabajadores produciendo recursos.</p>'}</div>`;}
 if(modal==='reset'){content=`<h2>¿Empezar desde cero?</h2><p>Esta acción sustituirá tu partida actual por una nueva historia. Antes de hacerlo, prepararemos una copia de seguridad local; te recomendamos exportar también tu guardado.</p><div class="row wrap">${btn('Sí, nueva historia','confirm-reset','primary')}${btn('Cancelar','close-modal','ghost')}</div>`;}
 if(modal==='import-confirm'){content=`<h2>¿Restaurar esta partida?</h2><p>La importación sustituirá el progreso actual. Conservaremos una copia local de seguridad de la partida que estás utilizando.</p><div class="row wrap">${btn('Importar y sustituir','confirm-import','primary')}${btn('Cancelar','close-modal','ghost')}</div>`;}
 if(modal==='complete'){content=`<div class="eyebrow">FIN DEL PRÓLOGO</div><h2>¡Te has convertido en comerciante!</h2><p>Empezaste sin nada, has levantado tu primer refugio, organizado trabajadores y fundado un puesto comercial.</p><p>En la <strong>versión 0.2</strong> llegarán los negocios, la fabricación de productos, talleres y rutas comerciales. Puedes seguir jugando y acumulando recursos hasta entonces.</p>`;}
 area.innerHTML=`<div class="modal-veil" data-do="backdrop"><div class="modal-card" role="dialog" aria-modal="true" aria-label="${esc(modal)}">${content}${closable?`<button class="ghost full modal-close" data-do="close-modal">${modal==='welcome'?'Empezar mi historia →':'Cerrar'}</button>`:''}</div></div>`;
}
let pendingImport=null;
async function handleFile(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>3000000){toast('El archivo es demasiado grande.',true);return;}try{pendingImport=parseImport(await file.text());modal='import-confirm';drawModal();}catch(err){toast(err.message||'No se pudo leer el archivo.',true)}}
async function handleClick(e){let b=e.target.closest('[data-do]');if(!b||b.disabled)return;let op=b.dataset.do,id=b.dataset.id;
 if(op==='backdrop'){if(e.target!==b)return;modal=null;drawModal();return;}
 if(op==='tab'){tab=id;window.scrollTo({top:0,behavior:'instant'});draw();return;}
 if(op==='close-modal'){modal=null;drawModal();return;}
 if(op==='open-event'){modal='event';drawModal();return;}
 if(op==='import'){document.getElementById('import-file').click();return;}
 if(op==='export'){const json=exportJson(game);const blob=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mendigo-emperador-v${RELEASE}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Archivo de partida generado.');return;}
 if(op==='save'){await saveGame(game);toast('Partida guardada.');return;}
 if(op==='reset'){modal='reset';drawModal();return;}
 if(op==='confirm-reset'){await backupGame(game);game=createGame((Date.now()>>>0)^0xD0F11);lastTick=Date.now();modal='welcome';queueSave();draw();toast('Una nueva historia comienza.');return;}
 if(op==='confirm-import'&&pendingImport){await backupGame(game);game=pendingImport;pendingImport=null;game.lastSavedAt=Date.now();lastTick=Date.now();modal=null;tab='home';await saveGame(game);draw();toast('Partida restaurada correctamente.');return;}
 let result;
 if(op==='work')result=action(game,id);
 else if(op==='purchase')result=purchase(game,id);
 else if(op==='hire')result=hire(game,id);
 else if(op==='fire')result=fire(game,id);
 else if(op==='trade')result=trade(game,id,b.dataset.kind,b.dataset.q);
 else if(op==='claim')result=claimQuest(game,id);
 else if(op==='contract')result=fulfill(game,id);
 else if(op==='choice'){result=chooseEvent(game,id,Number(b.dataset.q));if(result.ok)modal=null;}
 else if(op==='reserve'){result=setReserve(game,Number(document.getElementById('reserve')?.value));}
 if(result){toast(result.msg,!result.ok);if(result.ok){queueSave();if(game.owned.stall&&!game.stats.completionModalShown){game.stats.completionModalShown=true;modal='complete';queueSave();}}draw();}
}
function tick(){if(!game)return;let now=Date.now(),elapsed=(now-lastTick)/1000;lastTick=now;
 if(elapsed>3){advanceOffline(game,elapsed)}else if(elapsed>0)simulate(game,Math.min(elapsed,3));
 if(now-lastDraw>900&&!modal)draw();
 if(now-lastSave>10000){queueSave();lastSave=now;}
 if(now-lastBackup>90000){backupGame(game).catch(()=>{});lastBackup=now;}
}
async function boot(){try{game=await loadGame();const returning=!!game;
 if(!game)game=createGame((Date.now()>>>0)^0xF02A6);
 if(!checkState(game))throw new Error('La partida tiene un formato inesperado.');
 if(returning){const delta=Math.max(0,(Date.now()-game.lastSavedAt)/1000);if(delta>20)offlineResult=advanceOffline(game,delta);}
 lastTick=Date.now();lastSave=Date.now();lastBackup=Date.now();initShell();
 if(!returning)modal='welcome';else if(offlineResult&&offlineResult.real>60)modal='offline';
 draw();queueSave();setInterval(tick,250);
 window.addEventListener('pagehide',()=>{if(game)saveQuick(game);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){saveQuick(game);saveGame(game).catch(()=>{});}else{let d=(Date.now()-lastTick)/1000;if(d>3)advanceOffline(game,d);lastTick=Date.now();draw();}});
 if('serviceWorker' in navigator&&location.protocol.startsWith('http')){navigator.serviceWorker.register('./service-worker.js').catch(()=>{});}
 }catch(err){ROOT.innerHTML=`<main style="max-width:500px;margin:20vh auto;padding:25px;background:#24383a;border-radius:14px"><h1>Error al iniciar la partida</h1><p>Se ha producido un error al abrir los datos del juego. Si tienes una exportación, no borres los archivos del navegador.</p><pre style="white-space:pre-wrap;color:#efb0a4">${esc(err.message)}</pre><button onclick="location.reload()">Reintentar</button></main>`;console.error(err);}}
boot();
